version: 2

executor:
  docker:
    docker:
      - image: docker:edge-git

jobs:
  build_and_push:
    executor: docker
    parameters:
      name:
        type: string
      version:
        type: string
    environment:
      FOLDER: ./<< parameters.name >>
      IMAGE_NAME: sudomabider/<< parameters.name >>
      VERSION: << parameters.version >>
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build --cache-from=${IMAGE_NAME} --build-arg VERSION=${VERSION} -t ${IMAGE_NAME} ${FOLDER}
            docker tag ${IMAGE_NAME}:${VERSION} ${IMAGE_NAME}
      - deploy:
          name: Push Docker Image
          command: |
            echo $DOCKER_PASS | docker login --username $DOCKER_LOGIN --password-stdin
            docker push ${IMAGE_NAME}:${VERSION}
            docker push ${IMAGE_NAME}:latest

workflows:
  version: 2
  sqler:
    jobs:
      - build_and_push:
          context: docker-hub
          name: sqler
          version: 2.1
  php:
    jobs:
      - build_and_push:
          context: docker-hub
          name: php
          version: 7.3
    triggers:
      - schedule:
          cron: "0 18 * * *"

  php-nginx:
    jobs:
      - build_and_push:
          context: docker-hub
          name: php
          version: 7.3
    triggers:
      - schedule:
          cron: "0 18 * * *"
