version: 2.1

executors:
  docker:
    docker:
      - image: docker:edge-git

jobs:
  build_and_push:
    executor: docker
    parameters:
      serviceName:
        type: string
      serviceVersion:
        type: string
    environment:
      FOLDER: ./<< parameters.serviceName >>
      IMAGE_NAME: sudomabider/<< parameters.serviceName >>
      VERSION: << parameters.serviceVersion >>
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build --cache-from=${IMAGE_NAME} --build-arg VERSION=${VERSION} -t ${IMAGE_NAME} ${FOLDER}
            docker tag ${IMAGE_NAME}:${VERSION} ${IMAGE_NAME}
      - deploy:
          name: Push Docker Image
          command: |
            echo $DOCKER_PASS | docker login --username $DOCKER_LOGIN --password-stdin
            docker push ${IMAGE_NAME}:${VERSION}
            docker push ${IMAGE_NAME}:latest

workflows:
  sqler:
    jobs:
      - build_and_push:
          context: docker-hub
          serviceName: sqler
          serviceVersion: "2.1"
  php:
    jobs:
      - build_and_push:
          context: docker-hub
          serviceName: php
          serviceVersion: "7.3"
    triggers:
      - schedule:
          cron: "0 18 * * *"
          filters:
            branches:
              only:
                - master

  php-nginx:
    jobs:
      - build_and_push:
          context: docker-hub
          serviceName: php
          serviceVersion: "7.3"
    triggers:
      - schedule:
          cron: "0 18 * * *"
          filters:
            branches:
              only:
                - master
