name: Publish Image

on:
  push:
    branches:
      - master
    paths:
      - 'phpab/*'
      - '.github/workflows/phpab.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: sudomabider
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v1
      - name: Build
        uses: actions/docker/cli@master
        with: 
          args: build --pull -f phpab/Dockerfile --build-arg VERSION=1.25.6 -t sudomabider/phpab:1 phpab
      - name: Tag latest
        uses: actions/docker/cli@master
        with: 
          args: tag sudomabider/phpab:1.25.6 sudomabider/phpab:latest
      - name: Push versioned
        uses: actions/docker/cli@master
        with: 
          args: push sudomabider/phpab:1.25.6
      - name: Push latest
        uses: actions/docker/cli@master
        with: 
          args: push sudomabider/phpab:latest
